# k8s/backend-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: hr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-backend
  template:
    metadata:
      labels:
        app: hr-backend
    spec:
      containers:
      - name: backend
        image: nouromry/hr-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        
        # --- FIX IS HERE: ADDING HEALTH CHECKS ---
        livenessProbe:
          httpGet:
            path: /api/health # We will need to create this simple endpoint
            port: 5000
          initialDelaySeconds: 30  # Wait 30s before first probe
          periodSeconds: 15        # Check every 15s
          timeoutSeconds: 5        # Probe times out after 5s
          failureThreshold: 3      # Kill pod after 3 failures
        
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 15  # Wait 15s before first probe
          periodSeconds: 10        # Check every 10s
          timeoutSeconds: 5        # Probe times out after 5s