apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: hr
type: Opaque
data:
  # IMPORTANT: The values below must be base64 encoded
  JWT_SECRET: YXZlcnlsb25nYW5kc3VwZXJzZWNyZXRzdHJpbmdmb3Jqd3Q=
  EMAIL_USER: bm91cm9tcnkwNTNAZ21haWwuY29t
  EMAIL_PASS: bHdicSBvanJzIG96YWEgbHdlcw==
  CLOUDINARY_CLOUD_NAME: ZG5uanhrampmYg==
  CLOUDINARY_API_KEY: OTg3ODExNDExNzgyOTk4
  CLOUDINARY_API_SECRET: SE5qaUlHempHZEQycHlyenBxbjE0TWppejZV