name: CI - AI Model

on:
  push:
    paths:
      - 'ai-model/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build AI Model Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hr-aimodel ./ai-model

      - name: Push AI Model to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hr-aimodel
