name: CI - AI Model

on:
  push:
    branches: [ main ]
    paths:
      - 'ai-model/**'
      - '.github/workflows/ci-aimodel.yml'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the image and LOAD it into the local Docker daemon for Trivy to scan
      - name: Build image (load locally)
        uses: docker/build-push-action@v5
        with:
          context: ./ai-model
          tags: ${{ secrets.DOCKER_USERNAME }}/hr-aimodel:latest
          load: true      # <-- important so Trivy scans local image

      # Vulnerability scan (STRICT MODE)
      # Fails the job if HIGH/CRITICAL vulns are found
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/hr-aimodel:latest
          format: 'table'
          vuln-type: 'os,library'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '1'  # fail CI on HIGH/CRITICAL

      # If scan passes, push to Docker Hub
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hr-aimodel:latest
