# .github/workflows/ci-frontend.yml
name: CI - Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hr-frontend ./frontend

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.20.0 # <-- THE ONLY FIX NEEDED
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/hr-frontend'
          format: 'table'
          exit-code: '0' # This prevents the workflow from failing if vulnerabilities are found

      - name: Push Frontend to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hr-frontend