name: CI - Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hr-frontend ./frontend

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@latest
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/hr-frontend

      - name: Push Frontend to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hr-frontend
